<script setup lang="ts">
import { Search, MessageSquare, Eye, CheckCircle2, Star, ArrowRight, Plus, ThumbsUp, Flag, Reply, ChevronRight, Users, ShieldCheck } from 'lucide-vue-next'
import { forumTopics } from '~/utils/content'
const route=useRoute(), store=usePlatformStore()
const postDetail=computed(()=>route.path.startsWith('/forum/posts/'))
const topic=computed(()=>forumTopics.find(t=>t.id===route.path.split('/').at(-1))||forumTopics[0])
const replyText=ref(''), replies=ref([{id:1,author:'周致远',role:'数值方法编辑',time:'今天 09:42',text:'建议先把误差拆成离散误差和收敛误差。Re=100 的方腔流应优先核对中心线采样位置、边界角点处理和质量残差，不能只看速度残差。',likes:12,accepted:true},{id:2,author:'顾航',role:'社区成员',time:'今天 10:18',text:'我遇到过同样问题，最后发现参考数据使用的是无量纲坐标，而我的后处理脚本取了网格面而非单元中心。修正后误差从 6% 降到 1.2%。',likes:8,accepted:false}])
function addReply(){if(replyText.value.trim().length<5)return;replies.value.push({id:replies.value.length+1,author:store.user?.name||'本地访客',role:'注册用户',time:'刚刚',text:replyText.value.trim(),likes:0,accepted:false});replyText.value=''}
</script>
<template>
  <div v-if="!postDetail" class="page forum-page"><section class="page-hero slim"><div class="container"><span class="kicker">ENGINEERING COMMUNITY</span><h1>工程社区</h1><p>定位问题、分享可复现实验，并让高质量答案持续被找到。</p></div></section><div class="container forum-layout"><main><div class="forum-sections"><header><h2>讨论板块</h2><NuxtLink to="/forum/sections/all">查看全部 <ArrowRight :size="15"/></NuxtLink></header><div v-for="s in [{n:'新手问答',d:'基础概念、入门路径与平台使用',t:326,r:1280},{n:'理论与算法',d:'离散格式、求解器与数值验证',t:218,r:960},{n:'CFD 软件实践',d:'Fluent、OpenFOAM 与 STAR-CCM+',t:451,r:2304},{n:'Modelica',d:'语言、组件库与系统仿真',t:174,r:730}]" :key="s.n"><span>{{s.n.slice(0,1)}}</span><div><strong>{{s.n}}</strong><p>{{s.d}}</p></div><small>{{s.t}} 主题</small><small>{{s.r}} 回复</small><ArrowRight :size="17"/></div></div><div class="topic-stream"><div class="topic-tabs"><button class="active">最新</button><button>热门</button><button>待解决</button><button>精华</button><div class="page-search inline"><Search :size="16"/><input placeholder="搜索社区"></div></div><NuxtLink v-for="t in forumTopics" :key="t.id" :to="`/forum/posts/${t.id}`" class="forum-topic"><span class="topic-state" :class="t.status==='已解决'?'resolved':t.status==='精华'?'featured':''"><CheckCircle2 v-if="t.status==='已解决'"/><Star v-else-if="t.status==='精华'"/><MessageSquare v-else/></span><div><h2>{{t.title}}</h2><p><span>{{t.section}}</span> · 林昊 · {{t.time}}</p></div><span><MessageSquare :size="15"/>{{t.replies}}</span><span><Eye :size="15"/>{{t.views}}</span></NuxtLink></div></main><aside><button class="button large full"><Plus :size="18"/>发布新主题</button><div class="side-card"><strong>社区原则</strong><p>描述物理问题与边界条件，附上最小可复现案例，并说明已经尝试过的排查步骤。</p><a href="#">查看完整规范</a></div><div class="side-card"><strong>待解决问题</strong><NuxtLink v-for="t in forumTopics.filter(t=>t.status==='讨论中')" :key="t.id" :to="`/forum/posts/${t.id}`">{{t.title}}<small>{{t.replies}} 个回复</small></NuxtLink></div><div class="side-card stats"><div><Users/><span><strong>2,841</strong><small>工程用户</small></span></div><div><ShieldCheck/><span><strong>87%</strong><small>问题响应率</small></span></div></div></aside></div></div>
  <div v-else class="page post-page"><div class="container breadcrumb"><NuxtLink to="/forum">社区</NuxtLink><ChevronRight :size="14"/><span>{{topic.section}}</span><ChevronRight :size="14"/><span>{{topic.title}}</span></div><div class="container post-layout"><main><article class="post-card original"><header><div class="user-avatar">林</div><div><strong>林昊</strong><span>流体机械工程师 · 贡献值 426</span></div><small>#1 · 今天 08:56</small></header><div class="post-content"><div class="tag-row"><span>{{topic.section}}</span><span>方腔流</span><span>验证</span></div><h1>{{topic.title}}</h1><p>我使用 65×65 交错网格、SIMPLE 算法计算 Re=100 方腔顶盖驱动流。连续性残差降到 10⁻⁷，但与公开中心线速度数据相比仍有约 4% 偏差。</p><p>当前设置：速度欠松弛 0.7、压力欠松弛 0.3，对流项一阶迎风。请问应该优先检查离散格式、采样位置还是收敛判据？</p><pre><code>Re = 100\ngrid = 65 × 65\nmax(|mass imbalance|) = 7.2e-7</code></pre></div><footer><button><ThumbsUp :size="16"/>赞 6</button><button><Reply :size="16"/>回复</button><button><Flag :size="16"/>举报</button></footer></article><article v-for="r in replies" :key="r.id" class="post-card reply-card" :class="{accepted:r.accepted}"><div v-if="r.accepted" class="accepted-label"><CheckCircle2 :size="16"/>已采纳答案</div><header><div class="user-avatar">{{r.author.slice(0,1)}}</div><div><strong>{{r.author}}</strong><span>{{r.role}}</span></div><small>#{{r.id+1}} · {{r.time}}</small></header><div class="post-content"><p>{{r.text}}</p></div><footer><button><ThumbsUp :size="16"/>赞 {{r.likes}}</button><button><Reply :size="16"/>回复</button><button><Flag :size="16"/>举报</button></footer></article><form class="reply-editor" @submit.prevent="addReply"><h2>参与讨论</h2><textarea v-model="replyText" placeholder="写下可验证的建议或补充信息…"></textarea><div><small>回复草稿仅保存在当前页面</small><button class="button">发布回复</button></div></form></main><aside><div class="side-card"><strong>主题状态</strong><span class="status success">{{topic.status}}</span><dl><div><dt>回复</dt><dd>{{replies.length}}</dd></div><div><dt>浏览</dt><dd>{{topic.views}}</dd></div><div><dt>最后活跃</dt><dd>{{topic.time}}</dd></div></dl></div><div class="side-card"><strong>相关主题</strong><NuxtLink v-for="t in forumTopics.filter(x=>x.id!==topic.id).slice(0,3)" :key="t.id" :to="`/forum/posts/${t.id}`">{{t.title}}<small>{{t.replies}} 个回复</small></NuxtLink></div><div class="side-card"><strong>板块规则</strong><p>请隐藏敏感工程数据，不上传未经授权的商业软件许可或受限资料。</p></div></aside></div></div>
</template>
