<script setup lang="ts">
import { Boxes, Plus, FolderOpen, Library, ArrowRight, CheckCircle2, Code2, Play, Save, Search, FileCode2, ChevronRight, ChevronDown, Settings2, Bug, TerminalSquare, PanelBottomClose, GitBranch, Clock3, Copy, Archive, Activity, AlertTriangle, Download } from 'lucide-vue-next'
const route=useRoute(), router=useRouter(), store=usePlatformStore()
const hub=computed(()=>route.path==='/modelica')
const projectsPage=computed(()=>route.path==='/modelica/projects')
const editorPage=computed(()=>route.path.includes('/editor'))
const runPage=computed(()=>route.path.startsWith('/modelica/runs/'))
const librariesPage=computed(()=>route.path.startsWith('/modelica/libraries'))
const templatesPage=computed(()=>route.path==='/modelica/templates')
const projectId=computed(()=>route.path.split('/')[3]||'demo-project')
const project=computed(()=>store.projects.find(p=>p.id===projectId.value)||store.projects[0])
const code=ref(''), dirty=ref(false), compiling=ref(false), bottomTab=ref('problems'), newDialog=ref(false), newName=ref('转子动力学示例')
watch(project,p=>{if(p){code.value=p.code;dirty.value=false}},{immediate:true})
watch(code,()=>{if(project.value&&code.value!==project.value.code)dirty.value=true})
const diagnostics=computed(()=>{
  const out:{severity:string;line:number;code:string;text:string}[]=[]
  const lines=code.value.split('\n')
  if(!/\bmodel\s+\w+/.test(code.value)) out.push({severity:'error',line:1,code:'MO1001',text:'缺少顶层 model 声明'})
  if(!/end\s+\w+\s*;/.test(code.value)) out.push({severity:'error',line:lines.length,code:'MO1002',text:'模型缺少匹配的 end 语句'})
  if((code.value.match(/\(/g)||[]).length!==(code.value.match(/\)/g)||[]).length) out.push({severity:'error',line:1,code:'MO1003',text:'圆括号数量不匹配'})
  lines.forEach((line,i)=>{if(/Real\s+\w+/.test(line)&&!/[;=]/.test(line))out.push({severity:'warning',line:i+1,code:'MO2001',text:'声明可能缺少分号'})})
  return out
})
const modelStats=computed(()=>({parameters:(code.value.match(/parameter\s+/g)||[]).length,variables:(code.value.match(/\bReal\s+/g)||[]).length,equations:(code.value.match(/\n\s*[^/\n]+=/g)||[]).length}))
function save(){if(project.value){store.saveProject(project.value.id,code.value);dirty.value=false}}
async function compile(){save();compiling.value=true;bottomTab.value='output';await new Promise(r=>setTimeout(r,700));if(project.value){project.value.lastCompile=diagnostics.value.some(d=>d.severity==='error')?'有诊断':'成功';store.persist()}compiling.value=false}
async function run(){await compile();if(diagnostics.value.some(d=>d.severity==='error'))return;router.push(`/modelica/runs/${project.value?.id||'demo-project'}`)}
function create(){const p=store.createProject(newName.value);newDialog.value=false;router.push(`/modelica/projects/${p.id}/editor`)}
const time=Array.from({length:161},(_,i)=>i*.025)
const response=time.map(t=>.1*Math.exp(-.25*t)*Math.cos(9.997*t))
const velocity=time.map(t=>-.1*Math.exp(-.25*t)*(9.997*Math.sin(9.997*t)+.25*Math.cos(9.997*t)))
const templates=[{name:'质量—弹簧—阻尼',type:'机械',desc:'二阶线性系统与参数化实验',class:'MassSpringDamper'},{name:'双容腔热网络',type:'热学',desc:'热容、热阻与阶跃响应',class:'ThermalNetwork'},{name:'液压容腔与管路',type:'Fluid0D',desc:'可压缩容腔与管路阻力',class:'HydraulicCircuit'},{name:'单轴转子系统',type:'AeroEngine',desc:'转动惯量、负载与控制器',class:'SingleSpool'}]
const libraries=[{name:'Platform.Base',version:'1.0.0',classes:28,status:'已验证',desc:'类型、接口、单位与基础图标'},{name:'Platform.Math',version:'1.0.0',classes:34,status:'已验证',desc:'数学函数与插值工具'},{name:'Platform.Blocks',version:'1.0.0',classes:46,status:'已验证',desc:'连续、离散与逻辑信号块'},{name:'Platform.Thermal',version:'1.0.0',classes:22,status:'已验证',desc:'热容、导热、边界与传感器'},{name:'Platform.Fluid0D',version:'1.0.0',classes:31,status:'已验证',desc:'零维流体端口、容腔和阻力'},{name:'AeroEngine',version:'0.9.0',classes:25,status:'候选',desc:'转子、容腔、管路与特性图组件'}]
</script>

<template>
  <div v-if="hub" class="page modelica-hub">
    <section class="modelica-hero"><div class="container"><div><span class="kicker">SYSTEM SIMULATION</span><h1>Modelica 系统仿真工作台</h1><p>从源码与组件建立方程模型，经过检查、编译和版本化实验，得到可复现的动态响应。</p><div class="hero-actions"><NuxtLink to="/modelica/projects" class="button large"><Plus :size="18"/>新建项目</NuxtLink><NuxtLink to="/modelica/templates" class="button secondary large">从模板开始</NuxtLink><NuxtLink to="/modelica/libraries" class="text-link"><Library :size="17"/>浏览组件库</NuxtLink></div></div><div class="model-topology"><div class="topo-toolbar"><span>MassSpringDamper.mo</span><b>CHECKED</b></div><div class="topo-nodes"><div><Boxes/><span>Fixed</span></div><i></i><div><Boxes/><span>Spring</span></div><i></i><div><Boxes/><span>Mass</span></div></div><div class="topo-code"><span>equation</span><code>m * der(v) + c * v + k * x = 0;</code></div></div></div></section>
    <section class="container modelica-steps"><div v-for="(item,i) in [{t:'创建模型',d:'从空项目或可信模板开始',icon:Code2},{t:'检查编译',d:'定位语法、类型与结构问题',icon:Bug},{t:'运行实验',d:'锁定参数与求解器配置',icon:Play},{t:'分析结果',d:'对比曲线、事件与统计量',icon:Activity}]" :key="item.t"><span>0{{i+1}}</span><component :is="item.icon"/><h2>{{item.t}}</h2><p>{{item.d}}</p><ArrowRight v-if="i<3" class="step-arrow"/></div></section>
    <section class="section"><div class="container"><div class="section-heading"><div><span class="kicker">STARTER PROJECTS</span><h2>从可运行模板开始</h2></div><NuxtLink to="/modelica/templates" class="text-link">全部模板 <ArrowRight :size="16"/></NuxtLink></div><div class="template-grid"><NuxtLink v-for="t in templates" :key="t.name" to="/modelica/projects"><div><span>{{t.type}}</span><Boxes :size="26"/></div><h3>{{t.name}}</h3><p>{{t.desc}}</p><small>{{t.class}} · PlatformModelica-1.0</small></NuxtLink></div></div></section>
    <section class="modelica-support"><div class="container"><div><span class="kicker">LANGUAGE PROFILE</span><h2>明确支持的语言边界</h2><p>V1 覆盖模型、连接器、继承、方程、算法、事件和基础 DAE。编译器会明确拒绝未支持特性，不做静默降级。</p></div><div><span><CheckCircle2/>方程与算法</span><span><CheckCircle2/>connect / flow / stream</span><span><CheckCircle2/>when / pre / reinit</span><span><CheckCircle2/>IDA / CVODE 求解</span><span><AlertTriangle/>外部 C/Fortran 函数不支持</span><span><AlertTriangle/>任意系统命令不支持</span></div></div></section>
  </div>

  <div v-else-if="projectsPage" class="page account-like"><div class="container content-section"><header class="page-title-row"><div><span class="kicker">MY WORKSPACE</span><h1>Modelica 项目</h1><p>项目、源码修订和实验记录保存在本机浏览器。</p></div><button class="button" @click="newDialog=true"><Plus :size="17"/>新建项目</button></header><div class="list-toolbar"><div class="page-search inline"><Search :size="17"/><input placeholder="搜索项目…"></div><div class="view-toggle"><button class="active">表格</button><button>卡片</button></div></div><div class="project-table"><div class="table-head"><span>项目</span><span>顶层模型</span><span>依赖</span><span>最近编译</span><span>最近编辑</span><span></span></div><div v-for="p in store.projects" :key="p.id" class="table-row"><span><FileCode2 :size="19"/><span><strong>{{p.name}}</strong><small>{{p.id}}</small></span></span><span>{{p.template}}</span><span><i class="status success">已锁定</i></span><span><i class="status" :class="p.lastCompile==='成功'?'success':p.lastCompile==='有诊断'?'danger':''">{{p.lastCompile}}</i></span><span>{{new Date(p.updatedAt).toLocaleString('zh-CN')}}</span><span><NuxtLink :to="`/modelica/projects/${p.id}/editor`" class="button secondary small">打开</NuxtLink><button class="icon-button"><Archive :size="16"/></button></span></div></div></div></div>

  <div v-else-if="editorPage && project" class="modelica-ide">
    <div class="ide-toolbar"><div class="ide-project"><NuxtLink to="/modelica/projects"><ChevronRight class="back-chevron" :size="16"/></NuxtLink><strong>{{project.name}}</strong><span><GitBranch :size="13"/>main · 本地快照</span></div><label>顶层模型<select><option>{{project.template}}</option></select></label><div class="ide-actions"><span :class="{dirty}">{{dirty?'有未保存修改':'已保存'}}</span><button class="button secondary small" @click="save"><Save :size="15"/>保存</button><button class="button secondary small" :disabled="compiling" @click="compile"><Bug :size="15"/>{{compiling?'检查中':'检查模型'}}</button><button class="button small" @click="run"><Play :size="15"/>运行</button></div></div>
    <div class="ide-grid"><aside class="project-explorer"><div class="panel-title"><span>资源管理器</span><Plus :size="15"/></div><div class="tree-section"><strong><ChevronDown :size="14"/>{{project.name}}</strong><button class="active"><FileCode2 :size="15"/>{{project.template}}.mo</button><button><FileCode2 :size="15"/>package.mo</button></div><div class="tree-section"><strong><ChevronRight :size="14"/>依赖项</strong><button><Library :size="15"/>Platform.Base <small>1.0.0</small></button></div><div class="outline"><div class="panel-title">模型大纲</div><button>m <small>parameter Real</small></button><button>k <small>parameter Real</small></button><button>c <small>parameter Real</small></button><button>x <small>Real</small></button><button>v <small>Real</small></button></div></aside>
      <section class="editor-center"><div class="editor-tabs"><button class="active"><FileCode2 :size="14"/>{{project.template}}.mo <i v-if="dirty"></i></button></div><div class="code-editor"><div class="line-numbers"><span v-for="n in code.split('\n').length" :key="n">{{n}}</span></div><textarea v-model="code" spellcheck="false" aria-label="Modelica 源码编辑器"></textarea></div><div class="bottom-panel"><div class="bottom-tabs"><button :class="{active:bottomTab==='problems'}" @click="bottomTab='problems'">问题 <b>{{diagnostics.length}}</b></button><button :class="{active:bottomTab==='output'}" @click="bottomTab='output'">编译输出</button><button>任务</button><button>变量</button><PanelBottomClose :size="16"/></div><div v-if="bottomTab==='problems'" class="problems"><div v-if="!diagnostics.length" class="ide-empty"><CheckCircle2 :size="18"/>未发现语法与结构问题</div><button v-for="d in diagnostics" :key="d.code+d.line"><AlertTriangle :size="15" :class="d.severity"/><span>{{d.text}}</span><code>{{d.code}}</code><small>第 {{d.line}} 行</small></button></div><pre v-else class="compile-output"><code>[compiler] PlatformModelica 1.0.0\n[parser] parsed {{code.split('\n').length}} lines\n[semantic] {{modelStats.parameters}} parameters, {{modelStats.variables}} variables\n[flatten] {{modelStats.equations}} scalar equations\n{{diagnostics.length?'[diagnostic] '+diagnostics.length+' issue(s) found':'[success] model check completed'}}</code></pre></div></section>
      <aside class="model-inspector"><div class="panel-title"><span>检查器</span><Settings2 :size="15"/></div><div class="class-badge"><Boxes/><div><small>model</small><strong>{{project.template}}</strong></div></div><dl><div><dt>参数</dt><dd>{{modelStats.parameters}}</dd></div><div><dt>变量</dt><dd>{{modelStats.variables}}</dd></div><div><dt>方程</dt><dd>{{modelStats.equations}}</dd></div><div><dt>结构</dt><dd><i class="status success">平衡</i></dd></div></dl><div class="inspector-section"><strong>参数</strong><label>m <span>kg</span><input value="1.0"></label><label>k <span>N/m</span><input value="100.0"></label><label>c <span>N·s/m</span><input value="0.5"></label></div><div class="inspector-section"><strong>编译配置</strong><p>PlatformModelica-1.0</p><p>Compiler 1.0.0</p><p>Runtime ABI 1.0</p></div></aside></div>
  </div>

  <div v-else-if="runPage" class="page modelica-result"><div class="container"><div class="breadcrumb"><NuxtLink to="/modelica/projects">Modelica 项目</NuxtLink><ChevronRight :size="14"/><span>{{project?.name}}</span><ChevronRight :size="14"/><span>运行结果</span></div><header class="result-header"><div><span class="status-badge success"><CheckCircle2 :size="16"/>仿真成功</span><h1>{{project?.template || 'MassSpringDamper'}} · 基准实验</h1><p>RUN-{{projectId.toUpperCase()}} · Compiler 1.0.0 · Runtime ABI 1.0 · CVODE</p></div><button class="button"><Download :size="16"/>导出结果</button></header><section class="summary-grid"><div><small>积分区间</small><strong>0 – 4 s</strong></div><div><small>输出点</small><strong>161</strong></div><div><small>求解步数</small><strong>243</strong></div><div><small>事件</small><strong>0</strong></div><div><small>最大位移</small><strong>0.1000 m</strong></div></section><div class="model-result-grid"><aside class="variable-tree"><div class="page-search inline"><Search :size="15"/><input placeholder="筛选变量"></div><strong><ChevronDown :size="14"/>{{project?.template}}</strong><label><input type="checkbox" checked><i style="--series:#1769aa"></i>x <small>m</small></label><label><input type="checkbox" checked><i style="--series:#18a999"></i>v <small>m/s</small></label><label><input type="checkbox"><i></i>a <small>m/s²</small></label></aside><section class="model-chart"><div class="result-chart-head"><div><h2>动态响应</h2><p>位移 x 与速度 v</p></div><div class="view-toggle"><button class="active">曲线</button><button>统计</button></div></div><DataChart :x="time" :y="response" :y2="velocity" label="x / m" label2="v / m·s⁻¹"/></section><aside class="run-properties"><div class="panel-title">变量属性</div><strong>x</strong><dl><div><dt>类型</dt><dd>Real</dd></div><div><dt>单位</dt><dd>m</dd></div><div><dt>最小值</dt><dd>-0.0924</dd></div><div><dt>最大值</dt><dd>0.1000</dd></div><div><dt>终值</dt><dd>-0.0536</dd></div></dl></aside></div><section class="result-content"><h2>求解摘要</h2><div class="inline-alert success"><CheckCircle2 :size="18"/><span>初始化一致，积分器正常完成；未发生状态事件或步长失败。</span></div><div class="repro-id"><span>可复现标识</span><code>sha256:8c7f3d2…a91e · snapshot {{projectId}} · lock 1.0.0</code><button><Copy :size="15"/>复制</button></div></section></div></div>

  <div v-else-if="librariesPage" class="page"><section class="page-hero"><div class="container"><span class="kicker">COMPONENT LIBRARIES</span><h1>Modelica 组件库</h1><p>版本化、只读、经过接口检查与验证案例校核的工程组件。</p></div></section><div class="container content-section"><div class="library-grid"><div v-for="lib in libraries" :key="lib.name"><div><Library :size="24"/><span class="status" :class="lib.status==='已验证'?'success':'warning'">{{lib.status}}</span></div><h2>{{lib.name}}</h2><p>{{lib.desc}}</p><dl><div><dt>版本</dt><dd>{{lib.version}}</dd></div><div><dt>公开类</dt><dd>{{lib.classes}}</dd></div></dl><button class="button secondary small">查看组件 <ArrowRight :size="15"/></button></div></div></div></div>

  <div v-else class="page"><section class="page-hero"><div class="container"><span class="kicker">PROJECT TEMPLATES</span><h1>示例项目与模板</h1><p>每个模板包含锁定依赖、实验配置和参考结果。</p></div></section><div class="container content-section"><div class="template-grid large"><div v-for="t in templates" :key="t.name"><div><span>{{t.type}}</span><Boxes :size="28"/></div><h2>{{t.name}}</h2><p>{{t.desc}}</p><small>{{t.class}} · PlatformModelica-1.0</small><button class="button" @click="newName=t.name;create()">使用此模板</button></div></div></div></div>

  <div v-if="newDialog" class="modal-backdrop" @click.self="newDialog=false"><form class="dialog-card" @submit.prevent="create"><div><h2>新建 Modelica 项目</h2><button type="button" class="icon-button" @click="newDialog=false">×</button></div><label>项目名称<input v-model="newName" required maxlength="60"><small>项目会保存在当前浏览器中</small></label><label>模板<select><option>MassSpringDamper</option><option>空项目</option><option>ThermalNetwork</option></select></label><label>语言版本<select><option>PlatformModelica-1.0</option></select></label><footer><button type="button" class="button secondary" @click="newDialog=false">取消</button><button class="button">创建并打开</button></footer></form></div>
</template>
